server:
  error:
    whitelabel:
      enabled: false

# properties test
example:
  one:
    one: 1
    two: 2
    text: "text"
    hello: hello
  another:
    one: 1
    two: 2
    text: "text"
    hello: hello