server:
  error:
    whitelabel:
      enabled: false

# properties test
example:
  one:
    one: 1
    two: 2
    text: "text"
    hello: hello
  another:
    one: 1
    two: 2
    text: "text"
    hello: hello

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test?autoreconnect=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: beaniejoy