version: "3.8"
services:
  db-mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file:
      - env/mysql.env
  migration:
    build:
      context: ./flyway
      dockerfile: Dockerfile
    environment:
      FLYWAY_EDITION: community
    volumes:
      - ${PWD}/flyway/db-migration:/flyway/sql
      - ${PWD}/flyway/conf:/flyway/conf
    depends_on:
      - db-mysql