# for local test
version: "3.9"
services:
  service-db:
    image: mysql:8.0.33
    container_name: spring-service-db
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: beaniejoy
    ports:
      - "3306:3306"
  batch-db:
    image: mysql:8.0.33
    container_name: spring-batch-db
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: beaniejoy
    ports:
      - "3307:3306"