spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: springtest
  batch:
    jdbc:
      initialize-schema: always # 스키마설정 다시 실행 X
