spring:
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema:
  datasource:
    driver-class-name: org.h2.Driver
  jpa:
    # JPA 기준 초기화 실행시 spring 2.5 이상 버전인 경우 true 설정해야 함
    # (@Entity 기준으로 DDL 생성)
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: person.sql